server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: flow-manager-route
          uri: lb://flow-manager
          predicates:
            - Path=/api/v1/files/**, /api/v1/tasks/**
          filters:
            - AddRequestHeader=X-Gateway-Route, FlowManager-Direct
            - RemoveRequestHeader=Cookie

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: false